Frontend.yml only ignores: 1) error TS6192: All imports in import declaration are unused. 2) error TS6133: ‘X' is declared but its value is never read.